### ISSUE TITLE
Problems on examples

### ISSUE THREAD

**Issue by tuanphuc** [hugoam/mud-sample#1]
First I want to thank you for a great library.
I have problem on executing examples and I think that opening an issue here is more appropriate than the mud's repo.

So I run examples on my PC which runs on Ubuntu 16.04 + GTX 1070. Problems are
  -  Getting segmentation fault every time I hit tools on the top right hand side.
  -  Getting `../../../mud/3rdparty/bgfx/src/renderer_gl.cpp (1108): BGFX src API, type Undefined behavior, id 131222, severity Medium, 'Program undefined behavior warning: Sampler object 4 has depth compare enabled. It is being used with depth texture 6, by a program that samples it with a regular sampler. This is undefined beahvior.` in 02_camera_d, 04_sponza_d, 08_sky_d, 10_post_process_d and 20_meta_d
  -  Getting segmentation fault on 07_gltf_d, 12_ui_d and 16_visual_script_d
  -  07_prefabs_d shows only black screen
  -  abort (core dumped) on 13_live_ui_d, 14_live_gfx_d and 15_script_d

There isn't example 5 in bin directory, I think it might not be compiled.
I will try to fix those problems when I have time.

**Comment by tuanphuc** [comment]
I saw you comment out example 5 and 18 so I suppose that you're aware of the problems :)

**Comment by hugoam** [comment]
Hey ! Thanks for trying this library. Maybe you can run it in gdb and give me the stack trace after the segmentation fault happened ?

**Comment by tuanphuc** [comment]
I can’t do it this weekend so will try to do it on Monday.

**Comment by tuanphuc** [comment]
Here is the result of backtrace for the crash everytime I hit icons in the top right coner:
```
Thread 1 "00_cube_d" received signal SIGSEGV, Segmentation fault.
0x00007ffff6c42ffd in vg::addPosColor<3u> (stroker=0x8c25a0, srcPos=0x7fffffffb810, srcColor=0x7fffffffb800)
    at ../../../mud/3rdparty/vg-renderer/src/stroker.cpp:2569
2569			*dstPos128 = *srcPos128; // x0, y0, x1, y1
(gdb) backtrace
#0  0x00007ffff6c42ffd in vg::addPosColor<3u> (stroker=0x8c25a0, srcPos=0x7fffffffb810, srcColor=0x7fffffffb800)
    at ../../../mud/3rdparty/vg-renderer/src/stroker.cpp:2569
#1  0x00007ffff6c3f89f in vg::polylineStrokeAAThin<(vg::LineCap::Enum)0, (vg::LineJoin::Enum)0> (stroker=0x8c25a0, 
    mesh=0x7fffffffb970, vtx=0xf1d040, numPathVertices=4, color=4281611316, closed=true)
    at ../../../mud/3rdparty/vg-renderer/src/stroker.cpp:2332
#2  0x00007ffff6c201dd in vg::strokerPolylineStrokeAAThin (stroker=0x8c25a0, mesh=0x7fffffffb970, 
    vertexList=0xf1d040, numPathVertices=4, isClosed=true, color=4281611316, lineCap=vg::LineCap::Butt, 
    lineJoin=vg::LineJoin::Miter) at ../../../mud/3rdparty/vg-renderer/src/stroker.cpp:319
#3  0x00007ffff6f71f4a in vg::ctxStrokePathColor (ctx=0x9247b0, color=4281611316, width=1, flags=16)
    at ../../../mud/3rdparty/vg-renderer/src/vg.cpp:3185
#4  0x00007ffff6f6cb96 in vg::strokePath (ctx=0x9247b0, color=4281611316, width=1, flags=16)
    at ../../../mud/3rdparty/vg-renderer/src/vg.cpp:1491
#5  0x00007ffff6f65edc in mud::vgRenderer::stroke (this=0x8b9670, paint=...)
    at ../../../mud/src/ui-vg/VgRenderer.cpp:218
#6  0x00007ffff54a6108 in mud::VgRenderer::draw_rect (this=0x8b9670, rect=..., corners=..., inkstyle=...)
    at ../../../mud/src/ui/Render/Renderer.cpp:397
#7  0x00007ffff54a5333 in mud::VgRenderer::draw_background (this=0x8b9670, frame=..., rect=..., padded_rect=..., 
    content_rect=...) at ../../../mud/src/ui/Render/Renderer.cpp:281
#8  0x00007ffff54a4dcd in mud::VgRenderer::draw_frame (this=0x8b9670, frame=...)
    at ../../../mud/src/ui/Render/Renderer.cpp:238
#9  0x00007ffff54a49fb in mud::VgRenderer::render_frame (this=0x8b9670, frame=...)
    at ../../../mud/src/ui/Render/Renderer.cpp:195
#10 0x00007ffff54a46bd in mud::VgRenderer::render_layer (this=0x8b9670, layer=...)
    at ../../../mud/src/ui/Render/Renderer.cpp:133
#11 0x00007ffff54a4522 in mud::VgRenderer::<lambda(mud::Layer&)>::operator()(mud::Layer &) const (
    __closure=0x7fffffffbea0, layer=...) at ../../../mud/src/ui/Render/Renderer.cpp:106
#12 0x00007ffff54a6a3b in std::_Function_handler<void(mud::Layer&), mud::VgRenderer::render(mud::UiRenderTarget&)::<lambda(mud::Layer&)> >::_M_invoke(const std::_Any_data &, mud::Layer &) (__functor=..., __args#0=...)
    at /usr/include/c++/5/functional:1871
#13 0x00007ffff53d8249 in std::function<void (mud::Layer&)>::operator()(mud::Layer&) const (this=0x7fffffffbea0, 
    __args#0=...) at /usr/include/c++/5/functional:2267
#14 0x00007ffff53d6ef6 in mud::Layer::visit(std::function<void (mud::Layer&)> const&) (this=0x7ce4a0, visitor=...)
    at ../../../mud/src/ui/Frame/Layer.cpp:69
#15 0x00007ffff53d6f5f in mud::Layer::visit(std::function<void (mud::Layer&)> const&) (this=0x817320, visitor=...)
    at ../../../mud/src/ui/Frame/Layer.cpp:72
#16 0x00007ffff54a45a8 in mud::VgRenderer::render (this=0x8b9670, target=...)
    at ../../../mud/src/ui/Render/Renderer.cpp:107
#17 0x00007ffff54a3caa in mud::UiRenderTarget::render (this=0x81e970) at ../../../mud/src/ui/Render/Renderer.cpp:47
#18 0x00007ffff54ca14c in mud::UiWindow::next_frame (this=0x78df30) at ../../../mud/src/ui/UiWindow.cpp:173
#19 0x00007ffff6c47682 in mud::BgfxSystem::next_frame (this=0x7fffffffc150)
    at ../../../mud/src/bgfx/BgfxContext.cpp:110
#20 0x00007ffff6ed1c9e in mud::GfxSystem::next_frame (this=0x7fffffffc150) at ../../../mud/src/gfx/GfxSystem.cpp:145
#21 0x0000000000432c1e in mud::Shell::pump (this=0x7fffffffc0f0) at ../../../mud/src/mud/Shell.cpp:78
#22 0x0000000000432bb6 in mud::Shell::run(std::function<void (mud::Shell&)> const&, unsigned long) (
    this=0x7fffffffc0f0, func=..., iterations=0) at ../../../mud/src/mud/Shell.cpp:71
#23 0x000000000042481c in main (argc=1, argv=0x7fffffffcde8) at ../../../mud/example/00_cube/00_cube.cpp:56
```

**Comment by tuanphuc** [comment]
Here is the trace for 06_particles
```
Thread 1 "06_particles_d" received signal SIGABRT, Aborted.
0x00007ffff3d12428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) backtrace
#0  0x00007ffff3d12428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff3d1402a in __GI_abort () at abort.c:89
#2  0x00007ffff3d0abd7 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x44fadd "at < m_count", 
    file=file@entry=0x44fac0 "../../../mud/src/obj/Array.h", line=line@entry=49, 
    function=function@entry=0x44ff40 <mud::array<char const*>::operator[](unsigned long)::__PRETTY_FUNCTION__> "T& mud::array<T>::operator[](size_t) [with T = const char*; size_t = long unsigned int]") at assert.c:92
#3  0x00007ffff3d0ac82 in __GI___assert_fail (assertion=0x44fadd "at < m_count", 
    file=0x44fac0 "../../../mud/src/obj/Array.h", line=49, 
    function=0x44ff40 <mud::array<char const*>::operator[](unsigned long)::__PRETTY_FUNCTION__> "T& mud::array<T>::operator[](size_t) [with T = const char*; size_t = long unsigned int]") at assert.c:101
#4  0x000000000042ef33 in mud::array<char const*>::operator[] (this=0x7fffffffb900, at=64102455612276736)
    at ../../../mud/src/obj/Array.h:49
#5  0x00007ffff53892a9 in mud::ui::dropdown_input (parent=..., choices=..., value=@0x7fffffffb98c: 64102455612276736, 
    compact=true) at ../../../mud/src/ui/Button.cpp:219
#6  0x00007ffff6f532ef in mud::value_track_edit<glm::vec<3, float, (glm::qualifier)0> > (parent=..., track=...)
    at ../../../mud/src/gfx/Ui/ParticleEdit.h:21
#7  0x00007ffff6f501db in mud::<lambda(mud::ValueTrack<glm::vec<3, float, (glm::qualifier)0u> >&, mud::Widget&)>::operator()(mud::ValueTrack<glm::vec<3, float, (glm::qualifier)0> > &, mud::Widget &) const (__closure=0x799a00, value=..., 
    parent=...) at ../../../mud/src/gfx/Ui/GfxEdit.cpp:272
#8  0x00007ffff6f5053f in mud::<lambda(mud::Ref, mud::Widget&)>::operator()(mud::Ref, mud::Widget &) const (
    __closure=0x799a00, ref=..., args#0=...) at ../../../mud/src/obj/Util/DispatchDecl.h:16
#9  0x00007ffff6f5123b in std::_Function_handler<bool(mud::Ref, mud::Widget&), mud::dispatch_branch(mud::Dispatch<T_Return, T_Args ...>&, T_Function) [with T = mud::ValueTrack<glm::vec<3, float, (glm::qualifier)0u> >; T_Function = mud::declare_gfx_edit()::<lambda(mud::ValueTrack<glm::vec<3, float, (glm::qualifier)0u> >&, mud::Widget&)>; T_Return = bool; T_Args = {mud::Widget&}]::<lambda(mud::Ref, mud::Widget&)> >::_M_invoke(const std::_Any_data &, <unknown type in ../../linux64_gcc/bin/libmud_gfx_d.so, CU 0x108e522, DIE 0x111446a>, mud::Widget &) (__functor=..., 
    __args#0=<unknown type in ../../linux64_gcc/bin/libmud_gfx_d.so, CU 0x108e522, DIE 0x111446a>, __args#1=...)
    at /usr/include/c++/5/functional:1857
#10 0x00007ffff54e7bea in std::function<bool (mud::Ref, mud::Widget&)>::operator()(mud::Ref, mud::Widget&) const (
    this=0x799a00, __args#0=..., __args#1=...) at /usr/include/c++/5/functional:2267
#11 0x00007ffff54e6911 in mud::Dispatch<bool, mud::Widget&>::dispatch (
    this=0x7ffff7d6bdd0 <mud::LazyGlobal<mud::DispatchInput>::me()::instance>, ref=..., args#0=...)
    at ../../../mud/src/obj/Util/Dispatch.h:37
#12 0x00007ffff54e481c in mud::any_edit (parent=..., value=..., link=false, hint=mud::EditorHint::Inline)
    at ../../../mud/src/uio/Edit/Value.cpp:194
#13 0x00007ffff54d7f99 in mud::member_edit (parent=..., object=..., member=..., hint=mud::EditorHint::Inline)
    at ../../../mud/src/uio/Edit/Inspector.cpp:49
#14 0x00007ffff54d8081 in mud::member_named_edit (parent=..., object=..., member=...)
    at ../../../mud/src/uio/Edit/Inspector.cpp:61
#15 0x00007ffff54d8295 in mud::object_edit_rows (parent=..., object=...) at ../../../mud/src/uio/Edit/Inspector.cpp:96
#16 0x00007ffff54d8642 in mud::object_edit_table (parent=..., object=...)
    at ../../../mud/src/uio/Edit/Inspector.cpp:139
#17 0x00007ffff54d8818 in mud::object_edit (parent=..., object=..., hint=mud::EditorHint::Table)
    at ../../../mud/src/uio/Edit/Inspector.cpp:167
#18 0x00007ffff6f571c0 in mud::particle_edit (parent=..., system=..., generator=...)
    at ../../../mud/src/gfx/Ui/ParticleEdit.cpp:100
#19 0x00007ffff6f5729a in mud::particle_edit (parent=..., system=..., particles_call=...)
    at ../../../mud/src/gfx/Ui/ParticleEdit.cpp:111
#20 0x000000000042e617 in ex_06_particles (app=..., parent=..., dockbar=...)
    at ../../../mud/example/06_particles/06_particles.cpp:90
#21 0x000000000042e69a in pump (app=...) at ../../../mud/example/06_particles/06_particles.cpp:98
#22 0x000000000043a787 in std::_Function_handler<void (mud::Shell&), void (*)(mud::Shell&)>::_M_invoke(std::_Any_data const&, mud::Shell&) (__functor=..., __args#0=...) at /usr/include/c++/5/functional:1871
#23 0x00000000004420f5 in std::function<void (mud::Shell&)>::operator()(mud::Shell&) const (this=0x7fffffffccc0, 
    __args#0=...) at /usr/include/c++/5/functional:2267
#24 0x0000000000441524 in mud::Shell::pump (this=0x7fffffffc0e0) at ../../../mud/src/mud/Shell.cpp:77
#25 0x00000000004414cc in mud::Shell::run(std::function<void (mud::Shell&)> const&, unsigned long) (
    this=0x7fffffffc0e0, func=..., iterations=0) at ../../../mud/src/mud/Shell.cpp:71
#26 0x000000000042e75c in main (argc=1, argv=0x7fffffffcdd8) at ../../../mud/example/06_particles/06_particles.cpp:105
```

**Comment by hugoam** [comment]
Can you pull last version and try again ? Some of these issues were probably fixed over the week-end :)

**Comment by tuanphuc** [comment]
I did pull and recompile before testing :)

**Comment by hugoam** [comment]
Alright ! I thought I fixed similar issues. I'll look at the traces tonight and keep you posted if I find what's wrong, thanks for the reports.

**Comment by hugoam** [comment]
Hi, sorry it took so long to fix, I was working on releasing https://github.com/hugoam/toy
Now I can finally take some times to fix issues in mud. These two issues are fixed in https://github.com/hugoam/mud-sample/commit/2b91906fdda5494f13a4532f95e3b36e30e15240
(and https://github.com/hugoam/mud/commit/a3a9e6b1bcc381b41383f93d47715e435f684cdf for mud)
